name: build PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb
      - name: Set up CI environment
        run: .github/setup.sh
      - name: Set Maven memory limits
        run: echo "MAVEN_OPTS=-Xmx512m" >> $GITHUB_ENV
      - name: Execute the build
        run: xvfb-run --auto-servernum .github/build.sh

